ktor:
  application:
    modules:
      - me.szydelko.ApplicationKt.module
  deployment:
    port: 8080
jwt:
  issuer: "http://0.0.0.0:8080"
  domain: "http://0.0.0.0:8080"
  audience: "users"
  realm: "ktor sample app"
db:
  url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
  user: "root"
  driver: "org.h2.Driver"
  password: ""